version: '2'
services:
  www:
    image: stormerider/docker-apache-php
    volumes:
      - "./www:/var/www/html"
      - "./apache-logs:/var/log/apache2"
    ports:
      - "8010:80"
    restart: always
